### ISSUE TITLE
if the recipe result appears to be null due to missing variable, skip it nicely

### ISSUE THREAD

**Issue by Govindass** [ShaneBeee/SkRecipe#3]
right now if recipe result appears to be null, it throws big stacktrace and makes code to not continue, that's not nice, especially when you are forced to use "on skript load", you have to fix it, then restart server again to get the code after it working

**Comment by Govindass** [comment]
I just found that this error was caused by having "air" items in shapeless recipe, would be nice if air would just get ignored instead of error, maybe say a warning to not use air items in shapeless recipes, because making shapeless recipes in other addon(s) was allowing air

**Comment by ShaneBeee** [comment]
Hey, thanks for reporting this.
I actually already knew about this one. I've been trying to find a work around for it. 
I have some ideas so I will test them out and hopefully get an update out soon.

**Comment by ShaneBeee** [comment]
Ok Im working on a lil something something.

I set it up now so air (and non-items) will be automatically removed from the recipe. Your recipe will successfully load without errors.
Im also adding a config with a debug option, so if its true, you will see a message like this:
![Screen Shot 2019-11-23 at 1 34 42 PM](https://user-images.githubusercontent.com/20008482/69485574-2d384600-0df6-11ea-9535-832b91ac62bf.png)
I should probably make that a warning rather than an error, but you get the idea.

**Comment by Govindass** [comment]
thanks for fixing!

**Comment by ShaneBeee** [comment]
> thanks for fixing!

You're welcome. I'll get an update out soon.
